# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Region.create(nombre: 'Región de Arica y Parinacota', corfo: 'Norte Grande',codigo: 'XV',numero: '15')
Region.create(nombre: 'Región de Antofagasta', corfo: 'Norte Grande',codigo: 'II',numero: '2')
Region.create(nombre: 'Región de Tarapacá', corfo: 'Norte Grande',codigo: 'I',numero: '1')
Region.create(nombre: 'Región de Atacama', corfo: 'Norte Chico',codigo: 'III',numero: '3')
Region.create(nombre: 'Región de Coquimbo', corfo: 'Norte Chico',codigo: 'IV',numero: '4')
Region.create(nombre: 'Región de Valparaíso', corfo: 'Núcleo Central',codigo: 'XV',numero: '5')
Region.create(nombre: 'Región del Libertador General Bernardo O''Higgins', corfo: 'Núcleo Central',codigo: 'VI',numero: '6')
Region.create(nombre: 'Región del Maule', corfo: 'Núcleo Central',codigo: 'VII',numero: '7')
Region.create(nombre: 'Región del Biobío', corfo: 'Concepción y La Frontera',codigo: 'VIII',numero: '8')
Region.create(nombre: 'Región de la Araucanía', corfo: 'Concepción y La Frontera',codigo: 'IX',numero: '9')
Region.create(nombre: 'Región de los Ríos', corfo: 'Región de los Lagos',codigo: 'XIV',numero: '14')
Region.create(nombre: 'Región de Los Lagos', corfo: 'Región de los Lagos',codigo: 'X',numero: '10')
Region.create(nombre: 'Región de Aisén del General Carlos Ibáñez del Campo', corfo: 'Región de los Canales',codigo: 'XI',numero: '11')
Region.create(nombre: 'Región de Magallanes y de la Antártica Chilena', corfo: 'Región de los Canales',codigo: 'XIII',numero: '13')
Region.create(nombre: 'Región Metropolitana de Santiago', corfo: 'Núcleo Central',codigo: 'RM',numero: '13')

Provincia.create(nombre: 'Arica',regiones_id: (Region.find_by_nombre('Región de Arica y Parinacota')).id)
Provincia.create(nombre: 'Parinacota',regiones_id: (Region.find_by_nombre('Región de Arica y Parinacota')).id)
Provincia.create(nombre: 'El Tamarugal',regiones_id:(Region.find_by_nombre('Región de Tarapacá')).id)
Provincia.create(nombre: 'Iquique',regiones_id:(Region.find_by_nombre('Región de Tarapacá')).id)
Provincia.create(nombre: 'Tocopilla',regiones_id:(Region.find_by_nombre('Región de Antofagasta')).id)
Provincia.create(nombre: 'El Loa',regiones_id:(Region.find_by_nombre('Región de Antofagasta')).id)
Provincia.create(nombre: 'Antofagasta',regiones_id:(Region.find_by_nombre('Región de Antofagasta')).id)
Provincia.create(nombre: 'Chañaral',regiones_id:(Region.find_by_nombre('Región de Atacama')).id)
Provincia.create(nombre: 'Copiapó',regiones_id:(Region.find_by_nombre('Región de Atacama')).id)
Provincia.create(nombre: 'Huasco',regiones_id:(Region.find_by_nombre('Región de Atacama')).id)
Provincia.create(nombre: 'Elqui',regiones_id:(Region.find_by_nombre('Región de Coquimbo')).id)
Provincia.create(nombre: 'Limarí',regiones_id:(Region.find_by_nombre('Región de Coquimbo')).id)
Provincia.create(nombre: 'Choapa',regiones_id:(Region.find_by_nombre('Región de Coquimbo')).id)
Provincia.create(nombre: 'Petorca',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'Los Andes',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'San Felipe de Aconcagua',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'Quillota',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'Valparaíso',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'San Antonio',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'Isla de Pascua',regiones_id:(Region.find_by_nombre('Región de Valparaíso')).id)
Provincia.create(nombre: 'Cachapoal',regiones_id:(Region.find_by_nombre('Región del Libertador General Bernardo O''Higgins')).id)
Provincia.create(nombre: 'Colchagua',regiones_id:(Region.find_by_nombre('Región del Libertador General Bernardo O''Higgins')).id)
Provincia.create(nombre: 'Cardenal Caro',regiones_id:(Region.find_by_nombre('Región del Libertador General Bernardo O''Higgins')).id)
Provincia.create(nombre: 'Curicó',regiones_id:(Region.find_by_nombre('Región del Maule')).id)
Provincia.create(nombre: 'Talca',regiones_id:(Region.find_by_nombre('Región del Maule')).id)
Provincia.create(nombre: 'Linares',regiones_id:(Region.find_by_nombre('Región del Maule')).id)
Provincia.create(nombre: 'Cauquenes',regiones_id:(Region.find_by_nombre('Región del Maule')).id)
Provincia.create(nombre: 'Ñuble',regiones_id:(Region.find_by_nombre('Región del Biobío')).id)
Provincia.create(nombre: 'Biobío',regiones_id:(Region.find_by_nombre('Región del Biobío')).id)
Provincia.create(nombre: 'Concepción',regiones_id:(Region.find_by_nombre('Región del Biobío')).id)
Provincia.create(nombre: 'Arauco',regiones_id:(Region.find_by_nombre('Región del Biobío')).id)
Provincia.create(nombre: 'Malleco',regiones_id:(Region.find_by_nombre('Región de la Araucanía')).id)
Provincia.create(nombre: 'Cautín',regiones_id:(Region.find_by_nombre('Región de la Araucanía')).id)
Provincia.create(nombre: 'Valdivia',regiones_id:(Region.find_by_nombre('Región de los Ríos')).id)
Provincia.create(nombre: 'Ranco',regiones_id:(Region.find_by_nombre('Región de los Ríos')).id)
Provincia.create(nombre: 'Osorno',regiones_id:(Region.find_by_nombre('Región de Los Lagos')).id)
Provincia.create(nombre: 'Llanquihue',regiones_id:(Region.find_by_nombre('Región de Los Lagos')).id)
Provincia.create(nombre: 'Chiloé',regiones_id:(Region.find_by_nombre('Región de Los Lagos')).id)
Provincia.create(nombre: 'Palena',regiones_id:(Region.find_by_nombre('Región de Los Lagos')).id)
Provincia.create(nombre: 'Coihaique',regiones_id:(Region.find_by_nombre('Región de Aisén del General Carlos Ibáñez del Campo')).id)
Provincia.create(nombre: 'Aisén',regiones_id:(Region.find_by_nombre('Región de Aisén del General Carlos Ibáñez del Campo')).id)
Provincia.create(nombre: 'General Carrera',regiones_id:(Region.find_by_nombre('Región de Aisén del General Carlos Ibáñez del Campo')).id)
Provincia.create(nombre: 'Capitán Prat',regiones_id:(Region.find_by_nombre('Región de Aisén del General Carlos Ibáñez del Campo')).id)
Provincia.create(nombre: 'Última Esperanza',regiones_id:(Region.find_by_nombre('Región de Magallanes y de la Antártica Chilena')).id)
Provincia.create(nombre: 'Magallanes',regiones_id:(Region.find_by_nombre('Región de Magallanes y de la Antártica Chilena')).id)
Provincia.create(nombre: 'Tierra del Fuego',regiones_id:(Region.find_by_nombre('Región de Magallanes y de la Antártica Chilena')).id)
Provincia.create(nombre: 'Antártica Chilena',regiones_id:(Region.find_by_nombre('Región de Magallanes y de la Antártica Chilena')).id)
Provincia.create(nombre: 'Chacabuco',regiones_id:(Region.find_by_nombre('Región Metropolitana de Santiago')).id)
Provincia.create(nombre: 'Cordillera',regiones_id:(Region.find_by_nombre('Región Metropolitana de Santiago')).id)
Provincia.create(nombre: 'Maipo',regiones_id:(Region.find_by_nombre('Región Metropolitana de Santiago')).id)
Provincia.create(nombre: 'Talagante',regiones_id:(Region.find_by_nombre('Región Metropolitana de Santiago')).id)
Provincia.create(nombre: 'Melipilla',regiones_id:(Region.find_by_nombre('Región Metropolitana de Santiago')).id)
Provincia.create(nombre: 'Santiago',regiones_id:(Region.find_by_nombre('Región Metropolitana de Santiago')).id)

Comuna.create(nombre: 'Arica',provincias_id: ( Provincia.find_by_nombre('Arica')).id)
Comuna.create(nombre: 'Camarones',provincias_id: ( Provincia.find_by_nombre('Arica')).id)
Comuna.create(nombre: 'General Lagos',provincias_id: ( Provincia.find_by_nombre('Parinacota')).id)
Comuna.create(nombre: 'Putre',provincias_id: ( Provincia.find_by_nombre('Parinacota')).id)
Comuna.create(nombre: 'Camiña',provincias_id: ( Provincia.find_by_nombre('El Tamarugal')).id)
Comuna.create(nombre: 'Colchane',provincias_id: ( Provincia.find_by_nombre('El Tamarugal')).id)
Comuna.create(nombre: 'Huara',provincias_id: ( Provincia.find_by_nombre('El Tamarugal')).id)
Comuna.create(nombre: 'Pica',provincias_id: ( Provincia.find_by_nombre('El Tamarugal')).id)
Comuna.create(nombre: 'Pozo Almonte',provincias_id: ( Provincia.find_by_nombre('El Tamarugal')).id)
Comuna.create(nombre: 'Iquique',provincias_id: ( Provincia.find_by_nombre('Iquique')).id)
Comuna.create(nombre: 'Alto Hospicio',provincias_id: ( Provincia.find_by_nombre('Iquique')).id)
Comuna.create(nombre: 'María Elena',provincias_id: ( Provincia.find_by_nombre('Tocopilla')).id)
Comuna.create(nombre: 'Tocopilla',provincias_id: ( Provincia.find_by_nombre('Tocopilla')).id)
Comuna.create(nombre: 'Calama',provincias_id: ( Provincia.find_by_nombre('El Loa')).id)
Comuna.create(nombre: 'Ollagüe',provincias_id: ( Provincia.find_by_nombre('El Loa')).id)
Comuna.create(nombre: 'San Pedro de Atacama',provincias_id: ( Provincia.find_by_nombre('El Loa')).id)
Comuna.create(nombre: 'Antofagasta',provincias_id: ( Provincia.find_by_nombre('Antofagasta')).id)
Comuna.create(nombre: 'Mejillones',provincias_id: ( Provincia.find_by_nombre('Antofagasta')).id)
Comuna.create(nombre: 'Sierra Gorda',provincias_id: ( Provincia.find_by_nombre('Antofagasta')).id)
Comuna.create(nombre: 'Taltal',provincias_id: ( Provincia.find_by_nombre('Antofagasta')).id)
Comuna.create(nombre: 'Chañaral',provincias_id: ( Provincia.find_by_nombre('Chañaral')).id)
Comuna.create(nombre: 'Diego de Almagro',provincias_id: ( Provincia.find_by_nombre('Chañaral')).id)
Comuna.create(nombre: 'Copiapó',provincias_id: ( Provincia.find_by_nombre('Copiapó')).id)
Comuna.create(nombre: 'Caldera',provincias_id: ( Provincia.find_by_nombre('Copiapó')).id)
Comuna.create(nombre: 'Tierra Amarilla',provincias_id: ( Provincia.find_by_nombre('Copiapó')).id)
Comuna.create(nombre: 'Vallenar',provincias_id: ( Provincia.find_by_nombre('Huasco')).id)
Comuna.create(nombre: 'Freirina',provincias_id: ( Provincia.find_by_nombre('Huasco')).id)
Comuna.create(nombre: 'Huasco',provincias_id: ( Provincia.find_by_nombre('Huasco')).id)
Comuna.create(nombre: 'Alto del Carmen',provincias_id: ( Provincia.find_by_nombre('Huasco')).id)
Comuna.create(nombre: 'Andacollo',provincias_id: ( Provincia.find_by_nombre('Elqui')).id)
Comuna.create(nombre: 'Coquimbo',provincias_id: ( Provincia.find_by_nombre('Elqui')).id)
Comuna.create(nombre: 'La Higuera',provincias_id: ( Provincia.find_by_nombre('Elqui')).id)
Comuna.create(nombre: 'La Serena',provincias_id: ( Provincia.find_by_nombre('Elqui')).id)
Comuna.create(nombre: 'Paihuano',provincias_id: ( Provincia.find_by_nombre('Elqui')).id)
Comuna.create(nombre: 'Vicuña',provincias_id: ( Provincia.find_by_nombre('Elqui')).id)
Comuna.create(nombre: 'Ovalle',provincias_id: ( Provincia.find_by_nombre('Limarí')).id)
Comuna.create(nombre: 'Río Hurtado',provincias_id: ( Provincia.find_by_nombre('Limarí')).id)
Comuna.create(nombre: 'Monte Patria',provincias_id: ( Provincia.find_by_nombre('Limarí')).id)
Comuna.create(nombre: 'Combarbalá',provincias_id: ( Provincia.find_by_nombre('Limarí')).id)
Comuna.create(nombre: 'Punitaqui',provincias_id: ( Provincia.find_by_nombre('Limarí')).id)
Comuna.create(nombre: 'Illapel',provincias_id: ( Provincia.find_by_nombre('Choapa')).id)
Comuna.create(nombre: 'Salamanca',provincias_id: ( Provincia.find_by_nombre('Choapa')).id)
Comuna.create(nombre: 'Los Vilos',provincias_id: ( Provincia.find_by_nombre('Choapa')).id)
Comuna.create(nombre: 'Canela',provincias_id: ( Provincia.find_by_nombre('Choapa')).id)
Comuna.create(nombre: 'La Ligua',provincias_id: ( Provincia.find_by_nombre('Petorca')).id)
Comuna.create(nombre: 'Cabildo',provincias_id: ( Provincia.find_by_nombre('Petorca')).id)
Comuna.create(nombre: 'Zapallar',provincias_id: ( Provincia.find_by_nombre('Petorca')).id)
Comuna.create(nombre: 'Papudo',provincias_id: ( Provincia.find_by_nombre('Petorca')).id)
Comuna.create(nombre: 'Petorca',provincias_id: ( Provincia.find_by_nombre('Petorca')).id)
Comuna.create(nombre: 'Los Andes',provincias_id: ( Provincia.find_by_nombre('Los Andes')).id)
Comuna.create(nombre: 'San Esteban',provincias_id: ( Provincia.find_by_nombre('Los Andes')).id)
Comuna.create(nombre: 'Calle Larga',provincias_id: ( Provincia.find_by_nombre('Los Andes')).id)
Comuna.create(nombre: 'Rinconada',provincias_id: ( Provincia.find_by_nombre('Los Andes')).id)
Comuna.create(nombre: 'San Felipe',provincias_id: ( Provincia.find_by_nombre('San Felipe de Aconcagua')).id)
Comuna.create(nombre: 'Llaillay',provincias_id: ( Provincia.find_by_nombre('San Felipe de Aconcagua')).id)
Comuna.create(nombre: 'Putaendo',provincias_id: ( Provincia.find_by_nombre('San Felipe de Aconcagua')).id)
Comuna.create(nombre: 'Santa María',provincias_id: ( Provincia.find_by_nombre('San Felipe de Aconcagua')).id)
Comuna.create(nombre: 'Catemu',provincias_id: ( Provincia.find_by_nombre('San Felipe de Aconcagua')).id)
Comuna.create(nombre: 'Panquehue',provincias_id: ( Provincia.find_by_nombre('San Felipe de Aconcagua')).id)
Comuna.create(nombre: 'Quillota',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'La Calera',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'Limache',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'Nogales',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'Hijuelas',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'Olmué',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'La Cruz',provincias_id: ( Provincia.find_by_nombre('Quillota')).id)
Comuna.create(nombre: 'Valparaíso',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Viña del Mar',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Quilpué',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Villa Alemana',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Concón',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Quintero',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Puchuncaví',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Casablanca',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Juan Fernández',provincias_id: ( Provincia.find_by_nombre('Valparaíso')).id)
Comuna.create(nombre: 'Algarrobo',provincias_id: ( Provincia.find_by_nombre('San Antonio')).id)
Comuna.create(nombre: 'El Quisco',provincias_id: ( Provincia.find_by_nombre('San Antonio')).id)
Comuna.create(nombre: 'El Tabo',provincias_id: ( Provincia.find_by_nombre('San Antonio')).id)
Comuna.create(nombre: 'Cartagena',provincias_id: ( Provincia.find_by_nombre('San Antonio')).id)
Comuna.create(nombre: 'San Antonio',provincias_id: ( Provincia.find_by_nombre('San Antonio')).id)
Comuna.create(nombre: 'Santo Domingo',provincias_id: ( Provincia.find_by_nombre('San Antonio')).id)
Comuna.create(nombre: 'Isla de Pascua',provincias_id: ( Provincia.find_by_nombre('Isla de Pascua')).id)
Comuna.create(nombre: 'Codegua',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Coínco',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Coltauco',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Doñihue',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Graneros',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Las Cabras',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Machalí',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Malloa',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Olivar',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Peumo',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Pichidegua',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Quinta de Tilcoco',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Rancagua',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Requínoa',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Rengo',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Mostazal',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'San Vicente de Tagua Tagua',provincias_id: ( Provincia.find_by_nombre('Cachapoal')).id)
Comuna.create(nombre: 'Chépica',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Chimbarongo',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Lolol',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Nancagua',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Palmilla',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Peralillo',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Placilla',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Pumanque',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'San Fernando',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'Santa Cruz',provincias_id: ( Provincia.find_by_nombre('Colchagua')).id)
Comuna.create(nombre: 'La Estrella',provincias_id: ( Provincia.find_by_nombre('Cardenal Caro')).id)
Comuna.create(nombre: 'Litueche',provincias_id: ( Provincia.find_by_nombre('Cardenal Caro')).id)
Comuna.create(nombre: 'Marchigüe',provincias_id: ( Provincia.find_by_nombre('Cardenal Caro')).id)
Comuna.create(nombre: 'Navidad',provincias_id: ( Provincia.find_by_nombre('Cardenal Caro')).id)
Comuna.create(nombre: 'Paredones',provincias_id: ( Provincia.find_by_nombre('Cardenal Caro')).id)
Comuna.create(nombre: 'Pichilemu',provincias_id: ( Provincia.find_by_nombre('Cardenal Caro')).id)
Comuna.create(nombre: 'Curicó',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Hualañé',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Licantén',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Molina',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Rauco',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Romeral',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Sagrada Familia',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Teno',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Vichuquén',provincias_id: ( Provincia.find_by_nombre('Curicó')).id)
Comuna.create(nombre: 'Talca',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'San Clemente',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Pelarco',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Pencahue',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Maule',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'San Rafael',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Curepto',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Constitución',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Empedrado',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Río Claro',provincias_id: ( Provincia.find_by_nombre('Talca')).id)
Comuna.create(nombre: 'Linares',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'San Javier de Loncomilla',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Parral',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Villa Alegre',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Longaví',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Colbún',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Retiro',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Yerbas Buenas',provincias_id: ( Provincia.find_by_nombre('Linares')).id)
Comuna.create(nombre: 'Cauquenes',provincias_id: ( Provincia.find_by_nombre('Cauquenes')).id)
Comuna.create(nombre: 'Chanco',provincias_id: ( Provincia.find_by_nombre('Cauquenes')).id)
Comuna.create(nombre: 'Pelluhue',provincias_id: ( Provincia.find_by_nombre('Cauquenes')).id)
Comuna.create(nombre: 'Bulnes',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Chillán',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Chillán Viejo',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Cobquecura',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Coelemu',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Coihueco',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'El Carmen',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Ninhue',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Ñiquén',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Pemuco',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Pinto',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Portezuelo',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Quillón',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Quirihue',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Ránquil',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'San Carlos',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'San Fabián',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'San Ignacio',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'San Nicolás',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Treguaco',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Yungay',provincias_id: ( Provincia.find_by_nombre('Ñuble')).id)
Comuna.create(nombre: 'Alto Biobío',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Antuco',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Cabrero',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Laja',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Los Ángeles',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Mulchén',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Nacimiento',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Negrete',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Quilaco',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Quilleco',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'San Rosendo',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Santa Bárbara',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Tucapel',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Yumbel',provincias_id: ( Provincia.find_by_nombre('Biobío')).id)
Comuna.create(nombre: 'Concepción',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Coronel',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Chiguayante',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Florida',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Hualpén',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Hualqui',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Lota',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Penco',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'San Pedro de la Paz',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Santa Juana',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Talcahuano',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Tomé',provincias_id: ( Provincia.find_by_nombre('Concepción')).id)
Comuna.create(nombre: 'Arauco',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Cañete',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Contulmo',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Curanilahue',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Lebu',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Los Álamos',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Tirúa',provincias_id: ( Provincia.find_by_nombre('Arauco')).id)
Comuna.create(nombre: 'Angol',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Collipulli',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Curacautín',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Ercilla',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Lonquimay',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Los Sauces',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Lumaco',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Purén',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Renaico',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Traiguén',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Victoria',provincias_id: ( Provincia.find_by_nombre('Malleco')).id)
Comuna.create(nombre: 'Temuco',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Carahue',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Cholchol',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Cunco',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Curarrehue',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Freire',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Galvarino',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Gorbea',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Lautaro',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Loncoche',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Melipeuco',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Nueva Imperial',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Padre Las Casas',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Perquenco',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Pitrufquén',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Pucón',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Saavedra',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Teodoro Schmidt',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Toltén',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Vilcún',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Villarrica',provincias_id: ( Provincia.find_by_nombre('Cautín')).id)
Comuna.create(nombre: 'Valdivia',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Corral',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Lanco',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Los Lagos',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Mariquina',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Máfil',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Paillaco',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'Panguipulli',provincias_id: ( Provincia.find_by_nombre('Valdivia')).id)
Comuna.create(nombre: 'La Unión',provincias_id: ( Provincia.find_by_nombre('Ranco')).id)
Comuna.create(nombre: 'Futrono',provincias_id: ( Provincia.find_by_nombre('Ranco')).id)
Comuna.create(nombre: 'Lago Ranco',provincias_id: ( Provincia.find_by_nombre('Ranco')).id)
Comuna.create(nombre: 'Río Bueno',provincias_id: ( Provincia.find_by_nombre('Ranco')).id)
Comuna.create(nombre: 'Osorno',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'Puerto Octay',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'Purranque',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'Puyehue',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'Río Negro',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'San Pablo',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'San Juan de la Costa',provincias_id: ( Provincia.find_by_nombre('Osorno')).id)
Comuna.create(nombre: 'Calbuco',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Cochamó',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Fresia',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Frutillar',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Llanquihue',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Los Muermos',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Maullín',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Puerto Montt',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Puerto Varas',provincias_id: ( Provincia.find_by_nombre('Llanquihue')).id)
Comuna.create(nombre: 'Ancud',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Castro',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Chonchi',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Curaco de Vélez',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Dalcahue',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Puqueldón',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Queilén',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Quellón',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Quemchi',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Quinchao',provincias_id: ( Provincia.find_by_nombre('Chiloé')).id)
Comuna.create(nombre: 'Chaitén',provincias_id: ( Provincia.find_by_nombre('Palena')).id)
Comuna.create(nombre: 'Futaleufú',provincias_id: ( Provincia.find_by_nombre('Palena')).id)
Comuna.create(nombre: 'Hualaihué',provincias_id: ( Provincia.find_by_nombre('Palena')).id)
Comuna.create(nombre: 'Palena',provincias_id: ( Provincia.find_by_nombre('Palena')).id)
Comuna.create(nombre: 'Coihaique',provincias_id: ( Provincia.find_by_nombre('Coihaique')).id)
Comuna.create(nombre: 'Lago Verde',provincias_id: ( Provincia.find_by_nombre('Coihaique')).id)
Comuna.create(nombre: 'Aisén',provincias_id: ( Provincia.find_by_nombre('Aisén')).id)
Comuna.create(nombre: 'Cisnes',provincias_id: ( Provincia.find_by_nombre('Aisén')).id)
Comuna.create(nombre: 'Guaitecas',provincias_id: ( Provincia.find_by_nombre('Aisén')).id)
Comuna.create(nombre: 'Chile Chico',provincias_id: ( Provincia.find_by_nombre('General Carrera')).id)
Comuna.create(nombre: 'Río Ibáñez',provincias_id: ( Provincia.find_by_nombre('General Carrera')).id)
Comuna.create(nombre: 'Cochrane',provincias_id: ( Provincia.find_by_nombre('Capitán Prat')).id)
Comuna.create(nombre: 'O''Higgins',provincias_id: ( Provincia.find_by_nombre('Capitán Prat')).id)
Comuna.create(nombre: 'Tortel',provincias_id: ( Provincia.find_by_nombre('Capitán Prat')).id)
Comuna.create(nombre: 'Natales',provincias_id: ( Provincia.find_by_nombre('Última Esperanza')).id)
Comuna.create(nombre: 'Torres del Paine',provincias_id: ( Provincia.find_by_nombre('Última Esperanza')).id)
Comuna.create(nombre: 'Laguna Blanca',provincias_id: ( Provincia.find_by_nombre('Magallanes')).id)
Comuna.create(nombre: 'Punta Arenas',provincias_id: ( Provincia.find_by_nombre('Magallanes')).id)
Comuna.create(nombre: 'Río Verde',provincias_id: ( Provincia.find_by_nombre('Magallanes')).id)
Comuna.create(nombre: 'San Gregorio',provincias_id: ( Provincia.find_by_nombre('Magallanes')).id)
Comuna.create(nombre: 'Porvenir',provincias_id: ( Provincia.find_by_nombre('Tierra del Fuego')).id)
Comuna.create(nombre: 'Primavera',provincias_id: ( Provincia.find_by_nombre('Tierra del Fuego')).id)
Comuna.create(nombre: 'Timaukel',provincias_id: ( Provincia.find_by_nombre('Tierra del Fuego')).id)
Comuna.create(nombre: 'Cabo de Hornos',provincias_id: ( Provincia.find_by_nombre('Antártica Chilena')).id)
Comuna.create(nombre: 'Antártica',provincias_id: ( Provincia.find_by_nombre('Antártica Chilena')).id)
Comuna.create(nombre: 'Colina',provincias_id: ( Provincia.find_by_nombre('Chacabuco')).id)
Comuna.create(nombre: 'Lampa',provincias_id: ( Provincia.find_by_nombre('Chacabuco')).id)
Comuna.create(nombre: 'Tiltil',provincias_id: ( Provincia.find_by_nombre('Chacabuco')).id)
Comuna.create(nombre: 'Puente Alto',provincias_id: ( Provincia.find_by_nombre('Cordillera')).id)
Comuna.create(nombre: 'San José de Maipo',provincias_id: ( Provincia.find_by_nombre('Cordillera')).id)
Comuna.create(nombre: 'Pirque',provincias_id: ( Provincia.find_by_nombre('Cordillera')).id)
Comuna.create(nombre: 'San Bernardo',provincias_id: ( Provincia.find_by_nombre('Maipo')).id)
Comuna.create(nombre: 'Buin',provincias_id: ( Provincia.find_by_nombre('Maipo')).id)
Comuna.create(nombre: 'Paine',provincias_id: ( Provincia.find_by_nombre('Maipo')).id)
Comuna.create(nombre: 'Calera de Tango',provincias_id: ( Provincia.find_by_nombre('Maipo')).id)
Comuna.create(nombre: 'Isla de Maipo',provincias_id: ( Provincia.find_by_nombre('Talagante')).id)
Comuna.create(nombre: 'El Monte',provincias_id: ( Provincia.find_by_nombre('Talagante')).id)
Comuna.create(nombre: 'Padre Hurtado',provincias_id: ( Provincia.find_by_nombre('Talagante')).id)
Comuna.create(nombre: 'Peñaflor',provincias_id: ( Provincia.find_by_nombre('Talagante')).id)
Comuna.create(nombre: 'Talagante',provincias_id: ( Provincia.find_by_nombre('Talagante')).id)
Comuna.create(nombre: 'Curacaví',provincias_id: ( Provincia.find_by_nombre('Melipilla')).id)
Comuna.create(nombre: 'María Pinto',provincias_id: ( Provincia.find_by_nombre('Melipilla')).id)
Comuna.create(nombre: 'Melipilla',provincias_id: ( Provincia.find_by_nombre('Melipilla')).id)
Comuna.create(nombre: 'San Pedro',provincias_id: ( Provincia.find_by_nombre('Melipilla')).id)
Comuna.create(nombre: 'Alhué',provincias_id: ( Provincia.find_by_nombre('Melipilla')).id)
Comuna.create(nombre: 'Cerrillos',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Cerro Navia',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Conchalí',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'El Bosque',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Estación Central',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Huechuraba',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Independencia',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'La Cisterna',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'La Granja',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'La Florida',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'La Pintana',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'La Reina',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Las Condes',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Lo Barnechea',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Lo Espejo',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Lo Prado',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Macul',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Maipú',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Ñuñoa',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Pedro Aguirre Cerda',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Peñalolén',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Providencia',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Pudahuel',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Quilicura',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Quinta Normal',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Recoleta',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Renca',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'San Miguel',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'San Joaquín',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'San Ramón',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Santiago',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)
Comuna.create(nombre: 'Vitacura',provincias_id: ( Provincia.find_by_nombre('Santiago')).id)


User.create(nombre: 'admin',
    password: '123456',
    telefono: '123456789',
    email: 'admin@admin.cl',
    sueldo:'700000',
    rut: '92681378',
    password_confirmation: '123456',
    fechaingreso: "2017-07-20",
    admin: true)

User.create(nombre: 'admin1',
    password: '123456',
    telefono: '123456789',
    email: 'admin1@admin.cl',
    sueldo:'700000',
    rut: '16995885-8',
    password_confirmation: '123456',
    fechaingreso: "2017-07-20",
    admin: false)

